/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.monituxpos.Ventanas;

import com.monituxpos.Clases.Abono_Venta;
import com.monituxpos.Clases.Cuentas_Cobrar;
import com.monituxpos.Clases.Ingreso;
import com.monituxpos.Clases.Util;
import com.monituxpos.Clases.Venta;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel Cerrato
 */
public class V_Abono_Cliente extends javax.swing.JFrame {
    
    public int Secuencial_CTAC;
    public String Cliente_Nombre;
    public int Secuencial_Cliente;
    public int Secuencial_Usuario;
    public V_CTAS_Cobrar form;
    public double Gran_Total;
    
    public int Secuencial_Empresa;

    public String getCliente_Nombre() {
        return Cliente_Nombre;
    }

    public void setCliente_Nombre(String Cliente_Nombre) {
        this.Cliente_Nombre = Cliente_Nombre;
    }
    
    
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Abono_Cliente.class.getName());

    /**
     * Creates new form V_Abono_Cliente
     */
    public V_Abono_Cliente() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
    }

     public V_Abono_Cliente(int secuencial_ctac, int secuencial_cliente, String nombre_cliente, double gran_total,V_CTAS_Cobrar x) {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        
        
          
  Gran_Total = gran_total;
  this.setTitle("CTA. a Cobrar: " + secuencial_ctac);
  Secuencial_Empresa = V_Menu_Principal.getSecuencial_Empresa();
  Secuencial_Usuario = V_Menu_Principal.getSecuencial_Usuario();
  Secuencial_Cliente = secuencial_cliente;
  Secuencial_CTAC = secuencial_ctac;
  jLabel1.setText(nombre_cliente);
      form=x;  
        
    }

    
    
    private void cargarDatos() {
   

    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("MonituxPU");
    EntityManager em = emf.createEntityManager();

    try {
        // Consulta Cuentas_Cobrar
        List<Cuentas_Cobrar> ctaCobrar = em.createQuery(
            "SELECT c FROM Cuentas_Cobrar c WHERE c.Secuencial_Empresa = :empresa AND c.Secuencial_Cliente = :cliente AND c.Secuencial = :ctac",
            Cuentas_Cobrar.class)
            .setParameter("empresa", Secuencial_Empresa)
            .setParameter("cliente", Secuencial_Cliente)
            .setParameter("ctac", Secuencial_CTAC)
            .getResultList();

        for (Cuentas_Cobrar item : ctaCobrar) {
            jLabel7.setText(item.getGran_Total().toString());
            jLabel8.setText(item.getPagado().toString());
            jLabel9.setText(item.getSaldo().toString());
        }

        double valorRef = Math.round(Gran_Total * 100.0) / 100.0;
        double tolerancia = 0.05;

        // Consulta Ventas con filtro adicional en memoria
        List<Venta> ventas = em.createQuery(
            "SELECT v FROM Venta v WHERE v.Secuencial_Empresa = :empresa AND v.Secuencial_Cliente = :cliente AND v.Tipo = 'Credito'",
            Venta.class)
            .setParameter("empresa", Secuencial_Empresa)
            .setParameter("cliente", Secuencial_Cliente)
            .getResultList();

        for (Venta item : ventas) {
            if (Math.abs(item.getGran_Total() - valorRef) < tolerancia) {
                jLabel10.setText(String.valueOf(item.getSecuencial()));
                break; // si solo necesitas uno
            }
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al cargar datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        
        System.err.println(ex.getMessage());
    } finally {
        em.close();
        emf.close();
    }
}

    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(35, 32, 45));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pagado:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Recibir:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Saldo:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(35, 32, 45));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ver Abonos");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Registrar Abono");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("No. Factura:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 0));
        jLabel8.setText("0");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("0");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(11, 11, 11))
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre de Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
this.setLocationRelativeTo(null);
cargarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        //********************
        
        String textoAbono = jTextField1.getText();

    if (textoAbono != null && !textoAbono.trim().isEmpty()) {
        try {
            double abono = Double.parseDouble(textoAbono.replace(",", "."));
            double pagado = Double.parseDouble(jLabel8.getText().replace(",", "."));
            double saldo = Double.parseDouble(jLabel9.getText().replace(",", "."));

            double nuevoPagado = pagado + abono;
            double nuevoSaldo = saldo - abono;

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("MonituxPU");
            EntityManager em = emf.createEntityManager();

            try {
                em.getTransaction().begin();

                // Buscar cuenta por cobrar
                Cuentas_Cobrar ctaCobrar = em.createQuery(
                    "SELECT c FROM Cuentas_Cobrar c WHERE c.Secuencial = :ctac AND c.Secuencial_Empresa = :empresa",
                    Cuentas_Cobrar.class)
                    .setParameter("ctac", this.Secuencial_CTAC)
                    .setParameter("empresa", Secuencial_Empresa)
                    .getResultStream()
                    .findFirst()
                    .orElse(null);

                if (ctaCobrar != null) {
                    ctaCobrar.setSaldo(nuevoSaldo);
                    ctaCobrar.setPagado(nuevoPagado);
                    ctaCobrar.setSecuencial_Factura(Integer.parseInt(jLabel10.getText()));
                    ctaCobrar.setSecuencial_Empresa(Secuencial_Empresa);
                    ctaCobrar.setSecuencial_Cliente(Secuencial_Cliente);
                    ctaCobrar.setSecuencial_Usuario(V_Menu_Principal.getSecuencial_Usuario());

                    // Registrar ingreso
                    Ingreso ingreso = new Ingreso();
                    ingreso.setSecuencial_Empresa(Secuencial_Empresa);
                    ingreso.setSecuencial_Factura(Secuencial_CTAC);
                    ingreso.setSecuencial_Usuario(Secuencial_Usuario);
                    ingreso.setFecha(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")));
                    ingreso.setTotal(abono);
                    ingreso.setTipo_Ingreso("Pago Recibido");
                    ingreso.setDescripcion("Abono a CTA: " + Secuencial_CTAC + " de la Factura: " + jLabel10.getText());

                    em.persist(ingreso);

                    // Registrar abono
                    Abono_Venta abonoVenta = new Abono_Venta();
                    abonoVenta.setSecuencial_Empresa(Secuencial_Empresa);
                    abonoVenta.setSecuencial_Cliente(Secuencial_Cliente);
                    abonoVenta.setSecuencial_Usuario(Secuencial_Usuario);
                    abonoVenta.setSecuencial_CTAC(Secuencial_CTAC);
                    abonoVenta.setFecha(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss")));
                    abonoVenta.setMonto(abono);

                    em.persist(abonoVenta);

                    em.getTransaction().commit();

                    // Registrar actividad
                    Util.registrarActividad(Secuencial_Usuario,
                        "Ha registrado un abono a CTA:" + Secuencial_CTAC + " de " + jLabel1.getText() +
                        " por un monto de: " + jTextField1.getText() + " " +
                        " a Factura: " + jLabel10.getText(),
                        Secuencial_Empresa);

                    JOptionPane.showMessageDialog(null, "Abono registrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    form.Cargar_Datos_CTAS(Secuencial_Empresa);
                }

            } catch (Exception ex) {
                em.getTransaction().rollback();
                JOptionPane.showMessageDialog(null, "Error al registrar abono: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                em.close();
                emf.close();
            }

            cargarDatos();
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "El monto ingresado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "El monto a recibir es inválido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
        //********************



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed


        

        
        jTextField1.addKeyListener(new KeyAdapter() {
    @Override
    public void keyTyped(KeyEvent e) {
        char c = e.getKeyChar();

        // Permitir solo dígitos, retroceso y punto
        if (!Character.isDigit(c) && c != '.' && c != '\b') {
            e.consume(); // Bloquea el carácter
        }

        // Solo un punto decimal permitido
        if (c == '.' && jTextField1.getText().contains(".")) {
            e.consume();
        }
    }
});

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        V_Abonos vAbonos = new V_Abonos(Secuencial_CTAC, true, Cliente_Nombre, Integer.parseInt(jLabel10.getText()));
vAbonos.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new V_Abono_Cliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
