/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.monituxpos.Ventanas;

import com.monituxpos.Clases.Actividad;
import com.monituxpos.Clases.Categoria;
import com.monituxpos.Clases.Cliente;
import com.monituxpos.Clases.MonituxDBContext;
import java.awt.Color;
import com.monituxpos.Clases.Util;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;





/**
 *
 * @author Miguel Cerrato
 */
public class V_Categoria extends javax.swing.JFrame {
    
    
    
       public int Secuencial_Usuario= V_Menu_Principal.getSecuencial_Usuario();
    public int Secuencial_Empresa= V_Menu_Principal.getSecuencial_Empresa();//Cambiar esto
    public int Secuencial;
    
      private byte[] imagen;

public byte[] getImagen() {
    return imagen;
}

public void setImagen(byte[] imagen) {
    this.imagen = imagen;
}
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Categoria.class.getName());

    /**
     * Creates new form V_Categoria
     */
    public V_Categoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        labelImagen = new javax.swing.JLabel();
        labelImagen1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Descripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCategorias = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menu_Nuevo = new javax.swing.JMenuItem();
        Menu_Guardar = new javax.swing.JMenuItem();
        Menu_Eliminar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Menu_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categorias");
        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(35, 32, 40));

        jLabel2.setText("Nombre:");
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        labelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelImagen.setToolTipText("Click para escoger imagen.");
        labelImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImagenMouseClicked(evt);
            }
        });

        labelImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/camera.png"))); // NOI18N
        labelImagen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImagen1MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(35, 32, 40));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel6.setText("Buscar por:");
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Descripcion" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel3.setText("Descripcion:");
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setToolTipText("");

        txt_Descripcion.setColumns(20);
        txt_Descripcion.setLineWrap(true);
        txt_Descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_Descripcion);

        tableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoriasMouseClicked(evt);
            }
        });
        tableCategorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableCategoriasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableCategorias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelImagen1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(7, 7, 7))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(labelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Opciones");

        Menu_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/page_white.png"))); // NOI18N
        Menu_Nuevo.setText("Nuevo");
        Menu_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_NuevoActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Nuevo);

        Menu_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disk.png"))); // NOI18N
        Menu_Guardar.setText("Guardar");
        Menu_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_GuardarActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Guardar);

        Menu_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exclamation.png"))); // NOI18N
        Menu_Eliminar.setText("Eliminar");
        Menu_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_EliminarActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Eliminar);
        jMenu1.add(jSeparator1);

        Menu_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/door_out.png"))); // NOI18N
        Menu_Salir.setText("Salir");
        Menu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_NuevoActionPerformed

        Secuencial=0;
        
        txt_Nombre.setText("");
        txt_Descripcion.setText("");
    
        labelImagen.setIcon(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_NuevoActionPerformed

    private void Menu_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_GuardarActionPerformed

        //**********************************************************

        // Obtener imagen como byte[]
     
        byte[] imagenBytes = null;
Icon icono = labelImagen.getIcon();
if (icono instanceof ImageIcon) {
    Image imagen = ((ImageIcon) icono).getImage();
    BufferedImage copia = new BufferedImage(imagen.getWidth(null), imagen.getHeight(null), BufferedImage.TYPE_INT_RGB);
    Graphics2D g2d = copia.createGraphics();
    g2d.drawImage(imagen, 0, 0, null);
    g2d.dispose();

    imagenBytes = Util.comprimirImagen(copia, 100f); // Calidad ajustable
}

// Validaciones comunes
if (txt_Nombre.getText().isBlank()) {
    JOptionPane.showMessageDialog(null, "El nombre no puede estar vacío.");
    return;
}

if (txt_Descripcion.getText().isBlank()) {
    JOptionPane.showMessageDialog(null, "La descripción no puede estar vacía.");
    return;
}

EntityManager em = MonituxDBContext.getEntityManager();

try {
    if (Secuencial != 0) {
        // MODO EDICIÓN
        Categoria categoria = em.find(Categoria.class, Secuencial);
        if (categoria != null) {
            em.getTransaction().begin();
            categoria.setSecuencial_Empresa(Secuencial_Empresa);
            categoria.setDescripcion(txt_Descripcion.getText());
            categoria.setNombre(txt_Nombre.getText());

            if (imagenBytes != null) {
                categoria.setImagen(imagenBytes);
            }

            em.getTransaction().commit();

            Util.registrarActividad(Secuencial_Usuario, "Ha modificado la categoría: " + categoria.getNombre(), Secuencial_Empresa);
            JOptionPane.showMessageDialog(null, "Categoría actualizada correctamente.");
        }
    } else {
        // MODO CREACIÓN
        Categoria categoria = new Categoria();
        categoria.setSecuencial_Empresa(Secuencial_Empresa);
        categoria.setNombre(txt_Nombre.getText());
        categoria.setDescripcion(txt_Descripcion.getText());
        categoria.setImagen(imagenBytes);

        try {
            em.getTransaction().begin();
            em.persist(categoria);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Categoría creada correctamente.");
            Util.registrarActividad(Secuencial_Usuario, "Ha creado la categoría: " + categoria.getNombre(), Secuencial_Empresa);
        } catch (Exception e) {
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(null, "Error al crear categoría: Ya existe o los datos proporcionados no son válidos.");
            return;
        }
    }

    System.out.println("✅ Operación de categoría completada.");
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "❌ Error al guardar categoría: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}

dispose(); // Cierra el formulario actual

        
        
        //**********************************************************

    }//GEN-LAST:event_Menu_GuardarActionPerformed

    private void Menu_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_EliminarActionPerformed

       int res = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar esta categoría?", "Confirmación", JOptionPane.YES_NO_OPTION);

if (res == JOptionPane.YES_OPTION) {
    try {
        // Liberar imagen actual
        Icon icono = labelImagen.getIcon();
        if (icono instanceof ImageIcon) {
            ((ImageIcon) icono).getImage().flush(); // Libera recursos
        }
        labelImagen.setIcon(null);
        imagen = null; // Variable de clase si la usas
    } catch (Exception e) {
        // Silenciar errores de liberación de imagen
    }

    EntityManager em = MonituxDBContext.getEntityManager();

    try {
        Categoria categoria = em.createQuery(
            "SELECT c FROM Categoria c WHERE c.Secuencial = :secuencial AND c.Secuencial_Empresa = :empresa", Categoria.class)
            .setParameter("secuencial", this.Secuencial)
            .setParameter("empresa", Secuencial_Empresa)
            .getResultStream()
            .findFirst()
            .orElse(null);

        if (categoria != null) {
            // Mostrar imagen antes de eliminar (opcional)
            if (categoria.getImagen() != null && categoria.getImagen().length > 0) {
                try (ByteArrayInputStream bis = new ByteArrayInputStream(categoria.getImagen())) {
                    BufferedImage img = ImageIO.read(bis);
                    labelImagen.setIcon(new ImageIcon(img));
                } catch (IOException ex) {
                    labelImagen.setIcon(null);
                }
            } else {
                labelImagen.setIcon(null);
            }

            // Eliminar categoría
            em.getTransaction().begin();
            em.remove(categoria);
            em.getTransaction().commit();

            Util.registrarActividad(Secuencial_Usuario, "Ha eliminado la categoría: " + categoria.getNombre(), Secuencial_Empresa);
            JOptionPane.showMessageDialog(null, "Categoría eliminada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "❌ Error al eliminar categoría: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}


    }//GEN-LAST:event_Menu_EliminarActionPerformed

    private void Menu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_SalirActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_SalirActionPerformed

    private void labelImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImagenMouseClicked

        try {
            String imagenSeleccionada = Util.abrirDialogoSeleccionFilename();

            if (imagenSeleccionada != null && !imagenSeleccionada.trim().isEmpty()) {
                File archivoImagen = new File(imagenSeleccionada);

                if (archivoImagen.exists() && archivoImagen.isFile()) {
                    // Cargar imagen como BufferedImage
                    BufferedImage buffered = ImageIO.read(archivoImagen);

                    if (buffered != null) {
                        // Redimensionar al tamaño del JLabel
                        int ancho = labelImagen.getWidth();
                        int alto = labelImagen.getHeight();

                        Image imagenEscalada = buffered.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

                        // Mostrar imagen redimensionada en el JLabel
                        labelImagen.setIcon(new ImageIcon(imagenEscalada));

                        // Convertir imagen original (no escalada) a byte[] para guardar
                        ByteArrayOutputStream ms = new ByteArrayOutputStream();
                        ImageIO.write(buffered, "png", ms);
                        imagen = ms.toByteArray();
                    } else {
                        imagen = null;
                        System.err.println("Formato de imagen no soportado.");
                    }
                } else {
                    imagen = null;
                    System.err.println("Archivo no encontrado o inválido: " + imagenSeleccionada);
                }
            }
        } catch (IOException e) {
            imagen = null;
            e.printStackTrace();
            // VMenuPrincipal.MSG.showMSG("No se pudo cargar la imagen seleccionada.", "Error");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_labelImagenMouseClicked

    
   private void Filtrar(String campo, String valor) {
    tableCategorias.removeAll();

    DefaultTableModel model = (DefaultTableModel) tableCategorias.getModel();
    if (tableCategorias.getColumnCount() == 0) {
        model.setColumnIdentifiers(new String[] { "S", "Nombre", "Descripción", "Imagen" });

        tableCategorias.getColumnModel().getColumn(0).setPreferredWidth(30);   // S
        tableCategorias.getColumnModel().getColumn(1).setPreferredWidth(150);  // Nombre
        tableCategorias.getColumnModel().getColumn(2).setPreferredWidth(250);  // Descripción
        tableCategorias.getColumnModel().getColumn(3).setPreferredWidth(100);  // Imagen
    }

    model.setRowCount(0); // Limpiar filas existentes

    EntityManager em = MonituxDBContext.getEntityManager();

    try {
        String jpql = "SELECT c FROM Categoria c WHERE c.Secuencial_Empresa = :empresa AND FUNCTION('REPLACE', c." + campo + ", ' ', '') LIKE :valor";

        List<Categoria> categorias = em.createQuery(jpql, Categoria.class)
            .setParameter("empresa", Secuencial_Empresa)
            .setParameter("valor", "%" + valor.replace(" ", "") + "%")
            .getResultList();

        for (Categoria c : categorias) {
            model.addRow(new Object[] {
                c.getSecuencial(),
                c.getNombre(),
                c.getDescripcion(),
                c.getImagen() != null ? c.getImagen() : "Sin imagen"
            });
        }

        tableCategorias.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        if (tableCategorias.getRowCount() > 0) {
            tableCategorias.setRowSelectionInterval(0, 0);
        }

        System.out.println("✅ Categorías filtradas correctamente.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "❌ Error al filtrar categorías: " + e.getMessage());
        e.printStackTrace();
    }
}

    
    
    private void labelImagen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImagen1MouseClicked


        

        // Abrir ventana de captura
V_Captura_Imagen ventanaCamara = new V_Captura_Imagen(Secuencial, "Capturando...");
ventanaCamara.setModal(true);
ventanaCamara.setVisible(true);

// Obtener imagen capturada
BufferedImage imagenCapturada = V_Captura_Imagen.getImagen();

if (imagenCapturada != null) {
    // Liberar imagen anterior si existe
    if (labelImagen.getIcon() != null) {
        labelImagen.setIcon(null);
    }

    // Mostrar imagen redimensionada en JLabel
    Image imagenEscalada = imagenCapturada.getScaledInstance(
        labelImagen.getWidth(),
        labelImagen.getHeight(),
        Image.SCALE_SMOOTH
    );
    labelImagen.setIcon(new ImageIcon(imagenEscalada));

    // Convertir a byte[] (sin compresión personalizada)
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    try {
        ImageIO.write(imagenCapturada, "png", baos); // Usa "jpg" si deseas compresión
        imagen = baos.toByteArray(); // Variable byte[] para guardar la imagen
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al procesar la imagen capturada.", "Error", JOptionPane.ERROR_MESSAGE);
    }

} else {
    JOptionPane.showMessageDialog(null, "No se pudo capturar la imagen.", "Error", JOptionPane.ERROR_MESSAGE);
}



        // TODO add your handling code here:
    }//GEN-LAST:event_labelImagen1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased


         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String filtroSeleccionado = jComboBox2.getSelectedItem().toString();
        String valorFiltro = jTextField3.getText();

        Filtrar(filtroSeleccionado, valorFiltro); // Ejecuta solo al presionar Enter
    }
        
        
    }//GEN-LAST:event_jTextField3KeyReleased

    
      // Método auxiliar para obtener valor seguro de celda
        private String getCellValue(DefaultTableModel model, int row, int col) {
            Object value = model.getValueAt(row, col);
            return value != null ? value.toString() : "";

    }      
    
    
    private void tableCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoriasMouseClicked

       try {
        int rowIndex = tableCategorias.getSelectedRow();
        if (rowIndex < 0) return; // No hay fila seleccionada

        DefaultTableModel model = (DefaultTableModel) tableCategorias.getModel();

        // Asignar valores si existen
        Object secuencialObj = model.getValueAt(rowIndex, 0); // Columna "S"
        if (secuencialObj != null) {
            this.Secuencial = Integer.parseInt(secuencialObj.toString());
        }

        txt_Nombre.setText(getCellValue(model, rowIndex, 1));       // "Nombre"
        txt_Descripcion.setText(getCellValue(model, rowIndex, 2));  // "Descripción"

        // Cargar imagen desde la base de datos
        EntityManager em = MonituxDBContext.getEntityManager();

        Categoria categoria = em.createQuery(
            "SELECT c FROM Categoria c WHERE c.Secuencial = :Secuencial AND c.Secuencial_Empresa = :empresa", Categoria.class)
            .setParameter("Secuencial", this.Secuencial)
            .setParameter("empresa", Secuencial_Empresa)
            .getResultStream()
            .findFirst()
            .orElse(null);

        if (categoria != null && categoria.getImagen() != null && categoria.getImagen().length > 0) {
            try (ByteArrayInputStream bis = new ByteArrayInputStream(categoria.getImagen())) {
                BufferedImage img = ImageIO.read(bis);
                labelImagen.setIcon(new ImageIcon(img));
            } catch (IOException ex) {
                labelImagen.setIcon(null);
            }
        } else {
            labelImagen.setIcon(null);
        }

        System.out.println("✅ Categoría seleccionada cargada correctamente.");
    } catch (Exception ex) {
        labelImagen.setIcon(null);
        System.err.println("❌ Error al cargar categoría seleccionada: " + ex.getMessage());
        ex.printStackTrace();
    }
        
    }//GEN-LAST:event_tableCategoriasMouseClicked

    
   
    private void cargarDatos() {
    // Limpiar tabla
    DefaultTableModel model = new DefaultTableModel(
        new String[] { "S", "Nombre", "Descripcion" }, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Todas las celdas no editables
        }
    };

    EntityManager em = MonituxDBContext.getEntityManager();

    try {
        List<Categoria> lista = em.createQuery(
            "SELECT c FROM Categoria c WHERE c.Secuencial_Empresa = :empresa", Categoria.class)
            .setParameter("empresa", Secuencial_Empresa)
            .getResultList();

        for (Categoria c : lista) {
            model.addRow(new Object[] {
                c.getSecuencial(),
                c.getNombre(),
                c.getDescripcion()
            });
        }

        tableCategorias.setModel(model);
        tableCategorias.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Scroll horizontal

        // Estilo visual
        tableCategorias.setRowHeight(24);
        tableCategorias.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tableCategorias.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        tableCategorias.setGridColor(Color.LIGHT_GRAY);

        // Ajustar ancho de columnas automáticamente
        TableColumnModel columnModel = tableCategorias.getColumnModel();
        for (int col = 0; col < tableCategorias.getColumnCount(); col++) {
            int ancho = 75;
            for (int fila = 0; fila < tableCategorias.getRowCount(); fila++) {
                TableCellRenderer renderer = tableCategorias.getCellRenderer(fila, col);
                Component comp = tableCategorias.prepareRenderer(renderer, fila, col);
                ancho = Math.max(comp.getPreferredSize().width + 10, ancho);
            }
            columnModel.getColumn(col).setPreferredWidth(ancho);
        }

        System.out.println("✅ Categorías cargadas correctamente.");
    } catch (Exception e) {
        System.err.println("❌ Error al cargar categorías: " + e.getMessage());
    }
}

   private void primera_carga() {
    try {
        int rowIndex = 0;
        DefaultTableModel model = (DefaultTableModel) tableCategorias.getModel();

        // Asignar valores si existen
        Object secuencialObj = model.getValueAt(rowIndex, 0); // Columna "S"
        if (secuencialObj != null) {
            this.Secuencial = Integer.parseInt(secuencialObj.toString());
        }

        txt_Nombre.setText(getCellValue(model, rowIndex, 1));   // "Nombre"
        txt_Descripcion.setText(getCellValue(model, rowIndex, 2)); // "Descripcion"

        // Cargar imagen desde la base de datos
        EntityManager em = MonituxDBContext.getEntityManager();

        Categoria categoria = em.createQuery(
            "SELECT c FROM Categoria c WHERE c.Secuencial = :Secuencial AND c.Secuencial_Empresa = :empresa", Categoria.class)
            .setParameter("Secuencial", this.Secuencial)
            .setParameter("empresa", Secuencial_Empresa)
            .getResultStream()
            .findFirst()
            .orElse(null);

        if (categoria != null && categoria.getImagen() != null && categoria.getImagen().length > 0) {
            try (ByteArrayInputStream bis = new ByteArrayInputStream(categoria.getImagen())) {
                BufferedImage img = ImageIO.read(bis);
                labelImagen.setIcon(new ImageIcon(img));
            } catch (IOException ex) {
                labelImagen.setIcon(null);
            }
        } else {
            labelImagen.setIcon(null);
        }

        System.out.println("✅ Primera carga de categoría completada.");
    } catch (Exception ex) {
        labelImagen.setIcon(null);
        System.err.println("❌ Error en primera carga: " + ex.getMessage());
        ex.printStackTrace();
    }
}
 
    
    
    private void tableCategoriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCategoriasKeyReleased

         try {
        int rowIndex = tableCategorias.getSelectedRow();
        if (rowIndex < 0) return; // No hay fila seleccionada

        DefaultTableModel model = (DefaultTableModel) tableCategorias.getModel();

        // Asignar valores si existen
        Object secuencialObj = model.getValueAt(rowIndex, 0); // Columna "S"
        if (secuencialObj != null) {
            this.Secuencial = Integer.parseInt(secuencialObj.toString());
        }

        txt_Nombre.setText(getCellValue(model, rowIndex, 1));       // "Nombre"
        txt_Descripcion.setText(getCellValue(model, rowIndex, 2));  // "Descripción"

        // Cargar imagen desde la base de datos
        EntityManager em = MonituxDBContext.getEntityManager();

        Categoria categoria = em.createQuery(
            "SELECT c FROM Categoria c WHERE c.Secuencial = :Secuencial AND c.Secuencial_Empresa = :empresa", Categoria.class)
            .setParameter("Secuencial", this.Secuencial)
            .setParameter("empresa", Secuencial_Empresa)
            .getResultStream()
            .findFirst()
            .orElse(null);

        if (categoria != null && categoria.getImagen() != null && categoria.getImagen().length > 0) {
            try (ByteArrayInputStream bis = new ByteArrayInputStream(categoria.getImagen())) {
                BufferedImage img = ImageIO.read(bis);
                labelImagen.setIcon(new ImageIcon(img));
            } catch (IOException ex) {
                labelImagen.setIcon(null);
            }
        } else {
            labelImagen.setIcon(null);
        }

        System.out.println("✅ Categoría seleccionada cargada correctamente.");
    } catch (Exception ex) {
        labelImagen.setIcon(null);
        System.err.println("❌ Error al cargar categoría seleccionada: " + ex.getMessage());
        ex.printStackTrace();
    }
       
    }//GEN-LAST:event_tableCategoriasKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

cargarDatos();
primera_carga();
         this.getContentPane().setBackground(Color.black);
        
        setTitle("Monitux-POS v." + V_Menu_Principal.version);

// Asigna el secuencial del usuario

this.setLocationRelativeTo(null);

     if ("Vendedor".equals(V_Menu_Principal.getAcceso_Usuario())) {
    Menu_Eliminar.setVisible(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Eliminar;
    private javax.swing.JMenuItem Menu_Guardar;
    private javax.swing.JMenuItem Menu_Nuevo;
    private javax.swing.JMenuItem Menu_Salir;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelImagen1;
    private javax.swing.JTable tableCategorias;
    private javax.swing.JTextArea txt_Descripcion;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
