/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.monituxpos.Ventanas;

import com.monituxpos.Clases.Egreso;
import com.monituxpos.Clases.Ingreso;
import com.monituxpos.Clases.Usuario;
import com.monituxpos.Clases.Util;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel Cerrato
 */
public class V_Ingresos_Egresos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Ingresos_Egresos.class.getName());
public boolean isEgreso;

public int Secuencial_Empresa=V_Menu_Principal.getSecuencial_Empresa();;
public int Secuencial_Usuario=V_Menu_Principal.getSecuencial_Usuario();
public  V_Ingresos formulario_Principal_IN;
public  V_Egresos formulario_Principal_EG;
    /**
     * Creates new form V_Ingreso_Egreso
     */
    public V_Ingresos_Egresos() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        
    }

    
     public V_Ingresos_Egresos(V_Ingresos v_Ingresos) {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        formulario_Principal_IN = v_Ingresos;
        jButton1.setForeground(new Color(102,255,0));
        this.setTitle("Ingreso");
        
        
        
    }
     
     
      public V_Ingresos_Egresos(V_Egresos v_Egresos) {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        formulario_Principal_EG = v_Egresos;
        jButton1.setForeground(new Color(0,204,255));
        this.setTitle("Egreso");
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(35, 32, 45));

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Monto:");

        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Registrar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(null, this.Secuencial_Usuario);

EntityManagerFactory emf = Persistence.createEntityManagerFactory("MonituxPU");
EntityManager em = emf.createEntityManager();

try {
    // Validar monto
    String totalStr = txtTotal.getText().trim();
    double total;
    try {
        total = Double.parseDouble(totalStr);
        if (total <= 0) throw new NumberFormatException();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Debe ingresar un monto válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtener el objeto Usuario desde la base de datos
    Usuario usuario = em.find(Usuario.class, this.Secuencial_Usuario);
    if (usuario == null) {
        JOptionPane.showMessageDialog(this, "Usuario no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Formato de fecha con AM/PM
    String fecha = java.time.LocalDateTime.now()
        .format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm:ss a", new java.util.Locale("es", "ES")));

    em.getTransaction().begin();

    if (!this.isEgreso) {
        Ingreso ingresoManual = new Ingreso();
        ingresoManual.setFecha(fecha);
        ingresoManual.setTipo_Ingreso("Ingreso Manual");
        ingresoManual.setTotal(total);
        ingresoManual.setDescripcion(txtDescripcion.getText().trim());
        ingresoManual.setUsuario(usuario); // ← relación asignada
        ingresoManual.setSecuencial_Usuario(Secuencial_Usuario);
        ingresoManual.setSecuencial_Empresa(Secuencial_Empresa);
        ingresoManual.setSecuencial_Factura(null);

        em.persist(ingresoManual);
        em.getTransaction().commit();

        JOptionPane.showMessageDialog(this, "Ingreso registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
formulario_Principal_IN.cargarDatos();
        Util.registrarActividad(
            usuario.getSecuencial(),
            "Ha registrado un ingreso manual de " + ingresoManual.getTotal() +
            " por concepto de: " + ingresoManual.getDescripcion(),
            ingresoManual.getSecuencial_Empresa()
        );
    } else {
        Egreso egresoManual = new Egreso();
        egresoManual.setFecha(fecha);
        egresoManual.setTipo_Egreso("Egreso Manual");
        egresoManual.setTotal(total);
        egresoManual.setDescripcion(txtDescripcion.getText().trim());
        egresoManual.setUsuario(usuario); // ← relación asignada
        egresoManual.setSecuencial_Usuario(Secuencial_Usuario);
        egresoManual.setSecuencial_Empresa(Secuencial_Empresa);
        egresoManual.setSecuencial_Factura(null);

        em.persist(egresoManual);
        em.getTransaction().commit();
        formulario_Principal_EG.cargarDatos();
        JOptionPane.showMessageDialog(this, "Egreso registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        Util.registrarActividad(
            usuario.getSecuencial(),
            "Ha registrado un egreso manual de " + egresoManual.getTotal() +
            " por concepto de: " + egresoManual.getDescripcion(),
            egresoManual.getSecuencial_Empresa()
        );
    }

    this.dispose(); // Cierra la ventana actual

} catch (Exception ex) {
    if (em.getTransaction().isActive()) em.getTransaction().rollback();
    JOptionPane.showMessageDialog(this, "Error al registrar: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
} finally {
    em.close();
    emf.close();
}



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased


        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

this.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed



        
        txtTotal.addKeyListener(new KeyAdapter() {
    @Override
    public void keyTyped(KeyEvent e) {
        char c = e.getKeyChar();

        // Permitir solo dígitos, retroceso y punto
        if (!Character.isDigit(c) && c != '.' && c != '\b') {
            e.consume(); // Bloquea el carácter
        }

        // Solo un punto decimal permitido
        if (c == '.' && txtTotal.getText().contains(".")) {
            e.consume();
        }
    }
});
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new V_Ingresos_Egresos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
