/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.monituxpos.Ventanas;

import com.monituxpos.Clases.Kardex;
import com.monituxpos.Clases.MonituxDBContext;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import jakarta.persistence.TypedQuery;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Cerrato
 */
public class V_Kardex extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(V_Kardex.class.getName());

    public int Secuencial_Empresa=V_Menu_Principal.getSecuencial_Empresa(); 
    public int Secuencial_Producto;
    public String Codigo_Producto;
    
    /**
     * Creates new form V_Kardex
     */
    public V_Kardex() {
        initComponents();
    }

    
     public V_Kardex(int secuencialProducto,String codigoProducto) {
         
        initComponents();
        
        this.Secuencial_Producto= secuencialProducto;
        this.Codigo_Producto= codigoProducto;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.black);
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_salidas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_entradas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(486, 575));
        setPreferredSize(new java.awt.Dimension(494, 580));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(35, 32, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(495, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_salidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_salidas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 219, -1, 155));

        tabla_entradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla_entradas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 32, -1, 155));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Entradas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 6, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Salidas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 193, -1, -1));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jLabel5.setText("0");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 385, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete1.png"))); // NOI18N
        jLabel6.setText("0");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 385, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cargando...");
        jLabel2.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Leyendo Saldo...");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

      
setTitle("Monitux-POS v." + V_Menu_Principal.version);
    jLabel2.setText(Codigo_Producto);

    EntityManager em = MonituxDBContext.getEntityManager();

    try {
        filtrarKardex(Secuencial_Producto, "Entrada", tabla_entradas);
        filtrarKardex(Secuencial_Producto, "Salida", tabla_salidas);
        mostrarUltimoMovimientoKardex(Secuencial_Producto, Secuencial_Empresa, jLabel1);
        System.out.println("✅ Kardex cargado correctamente al abrir la ventana.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "❌ Error al cargar Kardex: " + ex.getMessage());
        ex.printStackTrace();
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    
public void filtrarKardex(int secuencialProducto, String movimiento, JTable tabla) {
    List<Kardex> kardexList = new ArrayList<>();
    EntityManager em = MonituxDBContext.getEntityManager();

    try {
        TypedQuery<Kardex> query = em.createQuery(
            "SELECT k FROM Kardex k JOIN FETCH k.producto " +
            "WHERE k.movimiento = :movimiento AND k.Secuencial_Producto = :secuencialProducto", Kardex.class);

        query.setParameter("movimiento", movimiento);
        query.setParameter("secuencialProducto", secuencialProducto);

        kardexList = query.getResultList();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "❌ Error al filtrar Kardex: " + ex.getMessage());
        ex.printStackTrace();
        return;
    }

    DefaultTableModel modelo = new DefaultTableModel(new Object[]{
        "S", "Fecha", "Descripción", "Cantidad", "Saldo"
    }, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    for (Kardex item : kardexList) {
        modelo.addRow(new Object[]{
            item.getSecuencial(),
            item.getFecha(),
            item.getDescripcion(),
            item.getCantidad(),
            item.getSaldo()
        });
    }

    tabla.setModel(modelo);
    tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    for (MouseListener ml : tabla.getMouseListeners()) {
        tabla.removeMouseListener(ml);
    }

    tabla.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            if (SwingUtilities.isLeftMouseButton(e)) {
                int fila = tabla.rowAtPoint(e.getPoint());
                if (fila != -1) {
                    tabla.setRowSelectionInterval(fila, fila);
                }
            }
        }
    });

    jLabel5.setText(String.valueOf(tabla_entradas.getModel().getRowCount()));
    jLabel6.setText(String.valueOf(tabla_salidas.getModel().getRowCount()));

    System.out.println("✅ Kardex filtrado correctamente.");
}


public void mostrarUltimoMovimientoKardex(int secuencialProducto, int secuencialEmpresa, JLabel label) {
    EntityManager em = null;

    try {
        em = MonituxDBContext.getEntityManager();
        if (em == null || !em.isOpen()) {
            throw new IllegalStateException("EntityManager no disponible.");
        }

       TypedQuery<Object[]> query = em.createQuery(
    "SELECT k.fecha, k.cantidad, p.Codigo, k.saldo, p.Descripcion, p.Tipo " +
    "FROM Kardex k JOIN k.producto p " +
    "WHERE p.Secuencial = :producto AND k.secuencial_empresa = :empresa " +
    "ORDER BY k.fecha DESC, k.secuencial DESC", Object[].class);


        query.setParameter("producto", secuencialProducto);
        query.setParameter("empresa", secuencialEmpresa);

        List<Object[]> resultados = query.setMaxResults(1).getResultList();

        if (!resultados.isEmpty()) {
            Object[] ultimo = resultados.get(0);
            String codigoProducto = String.valueOf(ultimo[2]);
            double saldoActual = Double.parseDouble(ultimo[3].toString());

            if (label != null) {
                label.setText("Saldo actual de " + codigoProducto + ": [ " + saldoActual + " ]");
            }
        } else {
            if (label != null) {
                label.setText("No se encontraron movimientos en el Kardex.");
            }
        }

        System.out.println("✅ Último movimiento de Kardex consultado correctamente.");
    } catch (Exception ex) {
        if (label != null) {
            label.setText("Error al consultar el Kardex: " + ex.getMessage());
        }
        ex.printStackTrace();
    } finally {
        if (em != null && em.isOpen()) {
            em.close();
        }
    }
}

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_entradas;
    private javax.swing.JTable tabla_salidas;
    // End of variables declaration//GEN-END:variables
}
